(print (equal? (real-number-recognizer (list #\1 #\0)) #t))
(print (equal? (real-number-recognizer (list #\0 #\1)) #f))
(print (equal? (real-number-recognizer (list #\1 #\. #\2)) #t))
(print (equal? (real-number-recognizer (list #\1 #\. #\.)) #f))
(print (equal? (real-number-recognizer (list #\. #\1)) #f))
(print (equal? (real-number-recognizer (list #\a #\b)) #f))

(print (equal? (bracket-recognizer (list #\()) #t))
(print (equal? (bracket-recognizer (list #\))) #t))
(print (equal? (bracket-recognizer (list #\( #\))) #f))

(print (equal? (identifier-recognizer (list #\a #\b)) #t))
(print (equal? (identifier-recognizer (list #\0 #\a #\b)) #f))
(print (equal? (identifier-recognizer (list #\a #\b #\!)) #t))
(print (equal? (identifier-recognizer (list #\a #\! #\b)) #f))
(print (equal? (identifier-recognizer (list #\! #\a #\b)) #f))
