(define (alphabet? char)
  (or (char=? char #\a)
      (char=? char #\b)
      (char=? char #\c)
      (char=? char #\d)
      (char=? char #\e)
      (char=? char #\f)
      (char=? char #\g)
      (char=? char #\h)
      (char=? char #\i)
      (char=? char #\j)
      (char=? char #\k)
      (char=? char #\l)
      (char=? char #\m)
      (char=? char #\n)
      (char=? char #\o)
      (char=? char #\p)
      (char=? char #\q)
      (char=? char #\r)
      (char=? char #\s)
      (char=? char #\t)
      (char=? char #\u)
      (char=? char #\v)
      (char=? char #\w)
      (char=? char #\x)
      (char=? char #\y)
      (char=? char #\z)))

(define (zero-to-nine? char)
  (or (char=? char #\0)
      (one-to-nine? char)))

(define (one-to-nine? char)
  (or (char=? char #\1)
      (char=? char #\2)
      (char=? char #\3)
      (char=? char #\4)
      (char=? char #\5)
      (char=? char #\6)
      (char=? char #\7)
      (char=? char #\8)
      (char=? char #\9)))
